---
- name: 'Converge'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Converge | apply r_pufky.srv.readarr'
      ansible.builtin.include_role:
        name: 'r_pufky.srv.readarr'

- name: 'Converge | toggle SSL'
  hosts: 'readarr-debian-12-enable_ssl-toggle'
  gather_facts: false
  tasks:
    - name: 'Converge | toggle SSL | apply r_pufky.srv.readarr'
      ansible.builtin.include_role:
        name: 'r_pufky.srv.readarr'
      vars:
        readarr_cfg_enable_ssl: false
