---
###############################################################################
# Enable SSL
###############################################################################
# SSL is enabled and toggled correctly.
#
# Tests:
# * /var/lib/readarr/readarr.pfx exists.
# * toggling ssl on, then off removes readarr.pfx.
#   <EnableSsl>False</EnableSsl>  # true requires ssl_cert
#   <SslCertPath>/var/lib/readarr/snakeoil.pfx</SslCertPath>
#   <SslCertPassword>testing</SslCertPassword>  # stored plaintext.
# * readarr_config_enable_ssl -- test when false w and w/o cert.

dependency:
  name: 'galaxy'
driver:
  name: 'podman'
provisioner:
  name: 'ansible'
  config_options:
    defaults:
      interpreter_python: 'auto_silent'
      callback_whitelist: 'profile_tasks, timer, yaml'
    ssh_connection:
      pipelining: false
  inventory:
    group_vars:
      all:
        readarr_config_enable_ssl: true
        readarr_config_ssl_cert_path: '{{
            lookup("env", "MOLECULE_PROJECT_DIRECTORY") ~
            "/molecule/cache/test.pfx"
          }}'
        readarr_config_ssl_cert_password: 'test'
        readarr_media_root_folders: ['/data/media']
        readarr_config_api_key: 'abcdef1234567890abcdef1234567890'
        repo_testing_enable: true
        repo_testing_versions:
          - comment: 'default'
            version: 'v0.4.10.2734'
            asset: '{{
                lookup("env", "MOLECULE_PROJECT_DIRECTORY") ~
                "/molecule/cache/" ~
                "Readarr.develop.0.4.10.2734.linux-core-x64.tar.gz"
              }}'
          - comment: 'toggle'
            version: 'v0.4.10.2734'
            asset: '{{
                lookup("env", "MOLECULE_PROJECT_DIRECTORY") ~
                "/molecule/cache/" ~
                "Readarr.develop.0.4.10.2734.linux-core-x64.tar.gz"
              }}'
platforms:
  - name: 'readarr-debian-12-enable_ssl'
    image: 'ghcr.io/hifis-net/debian-systemd:12'
    systemd: 'always'
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    command: '/lib/systemd/systemd'
    pre_build_image: true
  - name: 'readarr-debian-12-enable_ssl-toggle'
    image: 'ghcr.io/hifis-net/debian-systemd:12'
    systemd: 'always'
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    command: '/lib/systemd/systemd'
    pre_build_image: true
verifier:
  name: 'ansible'
lint: |
  set -e
  yamllint .
  ansible-lint .
scenario:
  test_sequence:
    # - 'dependency'
    # - 'cleanup'
    - 'destroy'
    - 'syntax'
    - 'create'
    - 'prepare'
    - 'converge'
    # - 'idempotence'  # Files created, extracted, created, deleted.
    # - 'side_effect'
    - 'verify'
    # - 'cleanup'
    - 'destroy'
