---
# yamllint disable rule:line-length
- name: 'Enable SSL | verify'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Enable SSL | verify | gather service status'
      ansible.builtin.service_facts:

    # Readarr will fail if configuration is bad (r_pufky.srv.systemd)
    - name: 'Enable SSL | verify | assert readarr.service active'
      ansible.builtin.assert:
        quiet: true
        that:
          - '"readarr.service" in ansible_facts.services'
          - 'ansible_facts["services"]["readarr.service"]["state"] == "running"'
        fail_msg: 'readarr.service should be enabled and running.'

- name: 'Enable SSL | verify | SSL enabled'
  hosts: 'readarr-debian-12-enable_ssl'
  gather_facts: false
  tasks:
    - name: 'Enable SSL | verify | SSL enabled | query config.xml'
      ansible.builtin.copy:
        src: 'files/config_ssl.xml'
        dest: '/var/lib/readarr/config.xml'
        owner: 'media'
        group: 'media'
        mode: '0600'
      check_mode: true
      diff: true
      register: _test_readarr_config_xml

    - name: 'Enable SSL | verify | SSL enabled | assert config.xml'
      ansible.builtin.assert:
        quiet: true
        that:
          - not _test_readarr_config_xml.changed
        fail_msg: >
          /var/lib/readarr/config.xml is not in expected format:
          {{ _test_readarr_config_xml.diff }}.

    - name: 'Enable SSL | verify | SSL enabled | query /var/lib/readarr/readarr.pfx'
      ansible.builtin.file:
        path: '/var/lib/readarr/readarr.pfx'
        owner: 'media'
        group: 'media'
        mode: '0640'
      check_mode: true
      diff: true
      register: _test_readarr_pfx

    - name: 'Enable SSL | verify | SSL enabled | assert /var/lib/readarr/readarr.pfx'
      ansible.builtin.assert:
        quiet: true
        that:
          - not _test_readarr_pfx.changed
        fail_msg: >
          /var/lib/readarr/readarr.pfx should exist with 0640 media:media
          {{ _test_readarr_pfx.diff }}

- name: 'Enable SSL | verify | SSL toggled'
  hosts: 'readarr-debian-12-enable_ssl-toggle'
  gather_facts: false
  tasks:
    - name: 'Enable SSL | verify | SSL toggled | query config.xml'
      ansible.builtin.copy:
        src: 'files/config_toggle.xml'
        dest: '/var/lib/readarr/config.xml'
        owner: 'media'
        group: 'media'
        mode: '0600'
      check_mode: true
      diff: true
      register: _test_readarr_config_xml

    - name: 'Enable SSL | verify | SSL toggled | assert config.xml'
      ansible.builtin.assert:
        quiet: true
        that:
          - not _test_readarr_config_xml.changed
        fail_msg: >
          /var/lib/readarr/config.xml is not in expected format:
          {{ _test_readarr_config_xml.diff }}.

    - name: 'Enable SSL | verify | SSL toggled | query /var/lib/readarr/readarr.pfx'
      ansible.builtin.file:
        path: '/var/lib/readarr/readarr.pfx'
        state: 'absent'
      check_mode: true
      register: _test_readarr_pfx

    - name: 'Enable SSL | verify | SSL toggled | assert /var/lib/readarr/readarr.pfx'
      ansible.builtin.assert:
        quiet: true
        that:
          - not _test_readarr_pfx.changed
        fail_msg: '/var/lib/readarr/readarr.pfx should not exist.'
