---
- name: 'Enable SSL | verify'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Enable SSL | verify | gather service status'
      ansible.builtin.service_facts:

    # Readarr will fail if configuration is bad (r_pufky.deb.systemd)
    - name: 'Enable SSL | verify | assert readarr.service active'
      ansible.builtin.assert:
        quiet: true
        that:
          - '"readarr.service" in ansible_facts.services'
          - 'ansible_facts["services"]["readarr.service"]["state"] == "running"'  # yamllint disable-line rule:line-length
        fail_msg: 'readarr.service should be enabled and running.'

- name: 'Enable SSL | verify | SSL enabled'
  hosts: 'readarr-debian-12-enable_ssl'
  gather_facts: false
  tasks:
    - name: 'Enable SSL | verify | SSL enabled | config.xml'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'copy.yml'
      vars:
        test_name: 'Enable SSL | verify | SSL enabled | config.xml'
        test_src: 'files/config_ssl.xml'
        test_file: '/var/lib/readarr/config.xml'
        test_owner: 'media'
        test_group: 'media'
        test_mode: '0600'

    - name: 'Enable SSL | verify | SSL enabled | /var/lib/readarr/readarr.pfx'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'file.yml'
      vars:
        test_name: >-
          Enable SSL | verify | SSL enabled |
          /var/lib/readarr/readarr.pfx
        test_file: '/var/lib/readarr/readarr.pfx'
        test_owner: 'media'
        test_group: 'media'
        test_mode: '0640'
        test_state: 'file'

- name: 'Enable SSL | verify | SSL toggled'
  hosts: 'readarr-debian-12-enable_ssl-toggle'
  gather_facts: false
  tasks:
    - name: 'Enable SSL | verify | SSL toggled | config.xml'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'copy.yml'
      vars:
        test_name: 'Enable SSL | verify | SSL toggled | config.xml'
        test_src: 'files/config_toggle.xml'
        test_file: '/var/lib/readarr/config.xml'
        test_owner: 'media'
        test_group: 'media'
        test_mode: '0600'

    - name: 'Enable SSL | verify | SSL toggled | /var/lib/readarr/readarr.pfx'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'file.yml'
      vars:
        test_name: >-
          Enable SSL | verify | SSL toggled |
          /var/lib/readarr/readarr.pfx
        test_file: '/var/lib/readarr/readarr.pfx'
        test_owner: '{{ omit }}'
        test_group: '{{ omit }}'
        test_mode: '{{ omit }}'
        test_state: 'absent'
