---
# yamllint disable rule:line-length
###############################################################################
# Readarr Config
###############################################################################
# Readarr is installed from source. Create systemd service and reload daemons,
# create required directories, certificates, set config, and start service.
# Service may not exist if first install.
#
# New config.xml options must be manually added to the template.
#
# Args:
#   _readarr_uid: int - readarr user UID.
#   _readarr_gid: int - readarr user GID.
#
# Reference:
# * https://github.com/Servarr/Wiki/blob/master/servarr/servarr-install-script.sh

- name: 'Config | Readarr service'
  ansible.builtin.include_role:
    name: 'r_pufky.srv.systemd'
  vars:
    systemd_daemon_reload_enable: true
    systemd_services:
      - name: 'readarr'
        state: 'present'
        drop_in: false
        unit:
          description: 'Readarr Daemon'
          after:
            - 'syslog.target'
            - 'network.target'
        service:
          type: 'simple'
          exec_start: ['{{ readarr_role_repo_extract_symlink_target }}/Readarr -nobrowser -data={{ readarr_service_data_dir }}']
          timeout_stop_sec: 20
          restart: 'always'  # always restart for periodic service restarts
          runtime_max_sec: '{{ "1d" if readarr_service_restart_daily_enable else "infinity" }}'
        exec:
          user: '{{ readarr_user }}'
          group: '{{ readarr_group }}'
          u_mask: '{{ readarr_service_u_mask }}'
        kill:
          kill_mode: 'process'
        install:
          wanted_by:
            - 'multi-user.target'

- name: 'Config | stop Readarr'
  ansible.builtin.service:
    name: 'readarr'
    state: 'stopped'

- name: 'Config | set {{ readarr_service_data_dir }}'
  ansible.builtin.file:
    path: '{{ readarr_service_data_dir }}'
    owner: '{{ readarr_user }}'
    group: '{{ readarr_group }}'
    mode: '0775'
    recurse: '{{ readarr_service_permissions_recursive_enable }}'
    state: 'directory'
  become: true

- name: 'Config | set {{ readarr_service_data_dir }}/readarr.pfx'  # noqa name[template] full path
  when: readarr_config_enable_ssl
  ansible.builtin.copy:
    src: '{{ readarr_config_ssl_cert_path }}'
    dest: '{{ readarr_service_data_dir }}/readarr.pfx'
    owner: '{{ readarr_user }}'
    group: '{{ readarr_group }}'
    mode: '0640'
    force: true

- name: 'Config | remove {{ readarr_service_data_dir }}/readarr.pfx'  # noqa name[template] full path
  when: not readarr_config_enable_ssl
  ansible.builtin.file:
    dest: '{{ readarr_service_data_dir }}/readarr.pfx'
    state: 'absent'

- name: 'Config | set {{ readarr_service_data_dir }}/update_script'  # noqa name[template] full path
  when: not readarr_config_update_mechanism
  ansible.builtin.copy:
    src: '{{ readarr_config_update_script_path }}'
    dest: '{{ readarr_service_data_dir }}/update_script'
    owner: '{{ readarr_user }}'
    group: '{{ readarr_group }}'
    mode: '0750'
    force: true

- name: 'Config | remove {{ readarr_service_data_dir }}/update_script'  # noqa name[template] full path
  when: readarr_config_update_mechanism
  ansible.builtin.file:
    dest: '{{ readarr_service_data_dir }}/update_script'
    state: 'absent'

# Use UID/GID as some media filesystems may be remote.
- name: 'Config | set media root folders'
  ansible.builtin.file:
    path: '{{ item }}'
    owner: '{{ _readarr_uid }}'
    group: '{{ _readarr_gid }}'
    mode: '{{ readarr_media_perms_folder }}'
    recurse: true
    state: 'directory'
  become: true
  loop: '{{ readarr_media_root_folders }}'

# Use UID/GID as some media filesystems may be remote.
- name: 'Config | set media root files'
  when: readarr_media_set_perms_file_enable
  ansible.builtin.shell: |
    find '{{ item }}' -type f -exec chmod {{ readarr_media_perms_file }} {}; chown {{ _readarr_uid }}:{{ _readarr_gid }} {} \;
  changed_when: false
  loop: '{{ readarr_media_root_folders }}'

# Writing the configuration back requires to_json, ansible.utils.to_xml, and
# xmltodict python3 package installed on both controller and node. Just use a
# template instead.
- name: 'Config | set Readarr configuration'
  notify: 'Handlers | restart readarr'
  ansible.builtin.template:
    src: 'config.xml.j2'
    dest: '{{ readarr_service_data_dir }}/config.xml'
    owner: '{{ readarr_user }}'
    group: '{{ readarr_group }}'
    mode: '0600'

- name: 'Config | start Readarr'
  ansible.builtin.service:
    name: 'readarr'
    state: 'started'
