---
###############################################################################
# Readarr Install
###############################################################################
# Install specified version from release.
#
# Args:
#   _readarr_migrate_metadata: list of str - files and directories to migrate.

- name: 'Install | packages'
  ansible.builtin.include_role:
    name: 'r_pufky.srv.apt'
  vars:
    apt_packages:
      - '{{ readarr_role_packages }}'
    apt_package_update_cache: true

# TODO(role): when officially released, switch to released tags only.
- name: 'Install | Readarr package {{ readarr_service_version }}'
  when: not readarr_service_force_config_only_enable
  ansible.builtin.include_role:
    name: 'r_pufky.srv.repo'
  vars:
    repo_release_owner: '{{ readarr_role_repo_release_owner }}'
    repo_release_repo: '{{ readarr_role_repo_release_repo }}'
    repo_release_tag: '{{ readarr_service_version }}'
    repo_release_pre_enable: true
    repo_release_specifier: '{{ readarr_role_repo_release_specifier }}'
    repo_release_asset: '{{ readarr_role_repo_release_asset }}'
    repo_file_owner: '{{ readarr_user }}'
    repo_file_group: '{{ readarr_group }}'
    repo_extract_dir: '{{ readarr_role_repo_extract_dir }}'
    repo_extract_symlink: '{{ readarr_role_repo_extract_symlink }}'
    repo_extract_migrate_files: '{{ _readarr_migrate_metadata }}'
    repo_extract_delete_old_versions:
      '{{ readarr_service_delete_old_versions_enable }}'
    repo_force_overwrite: '{{ readarr_service_force_overwrite }}'
    repo_extract_mode: 'a-st,o-rwx'
    repo_extract_extra_opts: '--strip-components=1'
