---
###############################################################################
# Readarr Install
###############################################################################
# Install specified version from release. Switch to released tags only when
# project is re-opened (or migrated to another base project).

- name: 'Install | packages'
  ansible.builtin.include_role:
    name: 'r_pufky.deb.apt'
  vars:
    apt_packages:
      - '{{ readarr_role_packages }}'
    apt_package_update_cache: true

- name: 'Install | Readarr package {{ _readarr_srv_version.raw }}'
  when: not _readarr_srv_force_config_only_enable.raw
  ansible.builtin.include_role:
    name: 'r_pufky.deb.repo'
  vars:
    repo_release_owner: '{{ readarr_role_repo_release_owner }}'
    repo_release_repo: '{{ readarr_role_repo_release_repo }}'
    repo_release_tag: '{{ _readarr_srv_version.raw }}'
    repo_release_pre_enable: true
    repo_release_specifier: '{{ readarr_role_repo_release_specifier }}'
    repo_release_asset: '{{ readarr_role_repo_release_asset }}'
    repo_file_owner: '{{ _readarr_srv_user._uid }}'
    repo_file_group: '{{ _readarr_srv_group._gid }}'
    repo_extract_dir: '{{ readarr_role_repo_extract_dir }}'
    repo_extract_symlink: '{{ readarr_role_repo_extract_symlink }}'
    repo_extract_migrate_files:
      '{{ _readarr_srv_migrate_metadata._files }}'
    repo_extract_delete_old_versions:
      '{{ _readarr_srv_delete_old_versions_enable.raw }}'
    repo_force_overwrite: '{{ _readarr_srv_force_overwrite.raw }}'
    repo_extract_mode: 'a-st,o-rwx'
    repo_extract_extra_opts: ['--strip-components=1']
