---
# yamllint disable rule:line-length
###############################################################################
# Readarr Install
###############################################################################
# Install specified version from github release.

- name: 'Install | packages'
  ansible.builtin.include_role:
    name: 'r_pufky.srv.apt'
  vars:
    apt_packages:
      - '{{ readarr_role_packages }}'
    apt_package_update_cache: true

# TODO(role): when officially released, switch to released tags only.
- name: 'Install | Readarr package {{ readarr_service_version }}'
  when: not readarr_service_force_config_only_enable
  ansible.builtin.include_role:
    name: 'r_pufky.srv.github'
  vars:
    github_repo_owner: '{{ readarr_role_github_owner }}'
    github_repo_repo: '{{ readarr_role_github_repo }}'
    github_repo_release: '{{ readarr_service_version }}'
    github_repo_archive_type: '{{ readarr_role_github_repo_archive_type }}'
    github_repo_pre_release_enable: true
    github_binary_enable: true
    github_binary_specifier: '{{ readarr_role_github_binary_specifier }}'
    github_binary_url: '{{ readarr_role_github_binary_url }}'
    github_file_owner: '{{ readarr_user }}'
    github_file_group: '{{ readarr_group }}'
    github_extract_dest: '{{ readarr_role_github_extract_dest }}'
    github_extract_symlink_target: '{{ readarr_role_github_extract_symlink_target }}'
    github_extract_migrate_files:
      - 'readarr.db'
      - 'readarr.db-shm'  # Readarr never closes DB's correctly.
      - 'readarr.db-wal'
      - 'logs.db'
      - 'logs.db-shm'
      - 'logs.db-wal'
    github_extract_delete_old_versions: '{{ readarr_service_delete_old_versions_enable }}'
    github_force_overwrite: '{{ readarr_service_force_overwrite }}'
    github_extract_mode: 'a-st,o-rwx'
    github_extract_extra_opts: '--strip-components=1'
