---
# yamllint disable rule:line-length
###############################################################################
# Readarr Prep
###############################################################################
# Prep Readarr variables for installation and upgrade. *arr services use the
# same codebase; any bugs or fixes should be checked for all related services.
#
# Generates:
#   _readarr_uid: int - readarr user UID.
#   _readarr_gid: int - readarr user GID.
#   _readarr_migrate_metadata: list of str - files and directories to migrate.
#
# Reference:
# * https://readarr.video/
# * https://wiki.servarr.com/readarr
# * https://github.com/Readarr/Readarr/releases
# * https://github.com/Servarr/Wiki/blob/master/servarr/servarr-install-script.sh
# yamllint enable rule:line-length

- name: 'Prep | assert SSL requirements'
  when: readarr_config_enable_ssl
  ansible.builtin.assert:
    quiet: true
    that:
      - readarr_config_ssl_cert_path | length > 0
    fail_msg: >
      readarr_config_enable_ssl=true requires
      readarr_config_ssl_cert_path set.

- name: 'Prep | assert update script requirements'
  when: not readarr_config_update_mechanism
  ansible.builtin.assert:
    quiet: true
    that:
      - readarr_config_update_script_path | length > 0
    fail_msg: >
      readarr_config_update_script_path must be set when
      readarr_config_update_mechanism=False.

- name: 'Prep | manage users'
  when: readarr_create_user
  ansible.builtin.include_role:
    name: 'r_pufky.srv.users'
    tasks_from: 'role_account_add.yml'
  vars:
    users_role_group: '{{ readarr_role_group }}'
    users_role_user: '{{ readarr_role_user }}'

- name: 'Prep | enumerate system user {{ readarr_user }}'
  ansible.builtin.user:
    name: '{{ readarr_user }}'
  check_mode: true
  changed_when: false
  register: _readarr_user_query

- name: 'Prep | parse system user UID/GID'
  ansible.builtin.set_fact:
    _readarr_uid: '{{ _readarr_user_query.uid }}'
    _readarr_gid: '{{ _readarr_user_query.group }}'

# Readarr does not consistently apply casing to XML settings and are frequently
# mis-spelled, inconsistently spelled, ordered, or strings used for boolean
# values; so we have to explicitly map those settings to the equivalent role
# settings. Order does not matter but will change based on WebUI usage and what
# values were changed last. This can lead to 'changed' configurations when no
# values were actually changed.
- name: 'Prep | build base config'
  ansible.builtin.set_fact:
    _readarr_config: {
      # General
      BindAddress: '{{ readarr_config_bind_address | default("*") }}',
      Port: '{{ readarr_config_port | default(8787) }}',
      UrlBase: '{{ readarr_config_url_base | default("") }}',
      InstanceName: '{{ readarr_config_instance_name | default("Readarr") }}',
      EnableSsl: '{{
          readarr_config_enable_ssl | default(false) |
          bool | string | capitalize
        }}',
      SslPort: '{{ readarr_config_ssl_port | default(6868) }}',
      SslCertPath: '{{
          "{{ readarr_service_data_dir }}/readarr.pfx"
          if readarr_config_enable_ssl | default(false) else
          ""
        }}',
      SslCertPassword: '{{ readarr_config_ssl_cert_password | default("") }}',
      AuthenticationMethod: '{{
          readarr_config_authentication_method | default("Forms") | capitalize
        }}',
      AuthenticationRequired: '{{
          "Enabled"
          if readarr_config_authentication_required | default(false) else
          "DisabledForLocalAddresses"
        }}',
      ApiKey: '{{
          readarr_config_api_key |
          default(inventory_hostname | md5 | truncate(32, true, ""))
        }}',
      LogLevel: '{{ readarr_config_log_level | default("info") | lower }}',
      # TODO(role): uncomment when readarr syncs to head.
      # LogSizeLimit: '{{ readarr_config_log_size_limit | default(1) }}',
      AnalyticsEnabled: '{{
          readarr_config_analytics_enabled | default(false) |
          bool | string | capitalize
        }}',
      Branch: '{{ readarr_config_branch | default("develop") | lower }}',
      UpdateAutomatically: '{{
          readarr_config_update_automatically | default(false) |
          bool | string | capitalize
        }}',
      UpdateMechanism: '{{
          "BuiltIn"
          if readarr_config_update_mechanism | default(true) else
          "Script"
        }}',
      UpdateScriptPath: '{{
          "{{ readarr_service_data_dir }}/update_script"
          if not readarr_config_update_mechanism | default(true) else
          ""
        }}',
      LaunchBrowser: '{{
          readarr_config_launch_browser | default(false) |
          bool | string | capitalize
        }}',
      # Settings > UI > Style
      Theme: '{{ readarr_config_theme | default("auto") | lower }}',
    }
    _readarr_migrate_metadata: '{{
        readarr_role_repo_extract_migrate_files
        if not readarr_service_migrate_metadata else
        readarr_role_repo_extract_migrate_files + ["MediaCover"]
      }}'

- name: 'Prep | add config extensions'
  when: readarr_config_extensions | length > 0
  ansible.builtin.set_fact:
    _readarr_config: '{{
        _readarr_config | combine(readarr_config_extensions, recursive=true)
      }}'
