---
# yamllint disable rule:line-length
###############################################################################
# Readarr Service Config (config.xml)
###############################################################################
# Externally stored service configuration for Readarr to successfully start.
# Additional settings are stored in the DB. WebUI locations are headers but all
# values are stored within config.xml.
#
# PascalCase: readarr_config_bind_address > BindAddress.
#
# Documented usage here reflect code, installer, and WebUI analysis. These may
# change over time and should be re-validated from time to time.

###############################################################################
# Settings > General > Host
###############################################################################

# Bind Readarr service to specified interface.
#
# Values:
#           *: bind to all available interfaces (default).
#        {IP}: bind to valid IP address ('127.0.0.1', '::', etc).
#   localhost: bind to localhost.
#
# Default: '*'.
readarr_config_bind_address: '*'

# HTTP port. Default: 8787.
readarr_config_port: 8787

# URL base for reverse proxy support. Default: '' (disabled).
readarr_config_url_base: ''

# Readarr application name for browser tab and syslog logs. Default: 'Readarr'.
readarr_config_instance_name: 'Readarr'

# Enable SSL? Default: False.
readarr_config_enable_ssl: false

# HTTPS port. Default: 6868.
readarr_config_ssl_port: 6868

# Path to PFX certificate.
#
# Sourced from ansible controller; automatically placed in
# readarr_service_data_dir/readarr.pfx with correct permissions. Readarr will be
# automatically configured to use the installed location.
#
# readarr_config_ssl_cert_path: 'host_vars/nzb.example.com/data/my_cert.pfx'
#
# Default: '' (disabled).
readarr_config_ssl_cert_path: ''

# PFX certificate password.
#
# WARNING: this is stored unencrypted in Readarr's config.xml.
#
# Default: '' (no password).
readarr_config_ssl_cert_password: ''

###############################################################################
# Settings > General > Security
###############################################################################

# Authentication method for user access.
#
# Values:
#       none: force user creation and auth selection WebUI (first run only).
#             basic or forms must be used after first run.
#      basic: browser pop-up for credentials.
#      forms: login page for credentials (use for password managers) (default).
#
# Default: 'forms'.
readarr_config_authentication_method: 'forms'

# Require authentication for all addresses?
#
# Always required for non-local connections. Disabling this will allow local
# addresses access WITHOUT authentication.
#
# Default: False.
readarr_config_authentication_required: false

# Readarr API key.
#
# Explicitly specify your key for consistent role application. Autogenerated
# value is deterministic.
#
# Special Case:
#   '': random 32 character alphanumeric hash
#
# Default: '{RANDOM}' (insecure idempotent API key based on hostname).
readarr_config_api_key: '{{ inventory_hostname | md5 | truncate(32, true, "") }}'

###############################################################################
# Settings > General > Logging
###############################################################################

# Readarr service log level.
#
# Values:
#    info: standard logging (default).
#   debug: log additional information.
#   trace: log everything.
#
# Default: 'info'.
readarr_config_log_level: 'info'

# Max log size before archiving (MB). Default: 1.
readarr_config_log_size_limit: 1

###############################################################################
# Settings > General > Analytics
###############################################################################

# Send usage and errors to Readarr developers?
#
# Includes browser, Readarr WebUI pages, error reporting, OS information, and
# runtime versions. Used to prioritize features and bug fixes.
#
# Default: False.
readarr_config_analytics_enabled: false

###############################################################################
# Settings > General > Updates (config.xml)
###############################################################################

# Readarr update branch to use.
#
# Values:
#   develop: beta/unstable - bleeding edge. may NOT be able to go back to main
#            after switching to this branch.  It is released as soon as code is
#            committed and passes all automated tests. This build may have not
#            been used by us or other users yet. There is no guarantee that it
#            will even run in some cases. This branch is only recommended for
#            advanced users. Issues and self investigation are expected in this
#            branch. Use this branch only if you know what you are doing and
#            are willing to get your hands dirty to recover a failed update.
#            This version is updated immediately.
#
# Default: 'develop'.
#
# Reference:
# * https://wiki.servarr.com/readarr/faq#how-do-i-update-readarr
readarr_config_branch: 'develop'

# Automatically download and install updates? Default: False.
readarr_config_update_automatically: false

# Automatic update mechanism.
#
# Non-docker installs only support BuiltIn or Script.
#
# Values:
#    True: use internal update mechanism (BuiltIn) (default).
#   False: use external update script (Script); requires
#             sonnar_config_update_script_path.
#
# Default: True.
#
# Reference:
# * https://wiki.servarr.com/readarr/settings#updates
readarr_config_update_mechanism: true

# Docker, External, Built-in, Script

# Custom script path for updates.
#
# Script should take an extracted update package and handle the remainder of
# the update process.
#
# Sourced from ansible controller; automatically placed in
# readarr_service_data_dir/update_script with correct permissions. Readarr will
# be automatically configured to use the installed location.
#
# readarr_config_update_script_path: 'host_vars/nzb.example.com/data/script.sh'
#
# Default: '' (disabled).
readarr_config_update_script_path: ''

###############################################################################
# Settings > General > Startup (config.xml)
###############################################################################

# Launch browser on startup?
#
# Only use when not running as a service. Removed entirely from the WebUI but
# used to be in settings > general > startup.
#
# Default: False.
readarr_config_launch_browser: false

###############################################################################
# Settings > UI > Style
###############################################################################

# Readarr WebUI theme.
#
# Values:
#    auto: use OS theme (default).
#   light: light mode.
#    dark: dark mode.
#
# Default: 'auto'.
readarr_config_theme: 'auto'
