---
- name: 'Default | verify'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Default | verify | gather service status'
      ansible.builtin.service_facts:

    - name: 'Default | verify | config.xml'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'copy.yml'
      vars:
        test_name: 'Default | verify | config.xml'
        test_src: 'files/config.xml'
        test_file: '/var/lib/readarr/config.xml'
        test_owner: 'media'
        test_group: 'media'
        test_mode: '0600'

    # Readarr will fail if configuration is bad (r_pufky.deb.systemd)
    - name: 'Default | verify | assert readarr.service active'
      ansible.builtin.assert:
        quiet: true
        that:
          - '"readarr.service" in ansible_facts.services'
          - 'ansible_facts["services"]["readarr.service"]["state"] == "running"'
        fail_msg: 'readarr.service should be enabled and running.'

    - name: 'Default | verify | /var/lib/readarr'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'file.yml'
      vars:
        test_name: 'Default | verify | /var/lib/readarr'
        test_file: '/var/lib/readarr'
        test_owner: 'media'
        test_group: 'media'
        test_mode: '0775'
        test_state: 'directory'

    - name: 'Default | verify | /var/lib/readarr/update_script'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'file.yml'
      vars:
        test_name: 'Default | verify | /var/lib/readarr/update_script'
        test_file: '/var/lib/readarr/update_script'
        test_owner: '{{ omit }}'
        test_group: '{{ omit }}'
        test_mode: '{{ omit }}'
        test_state: 'absent'

    - name: 'Default | verify | /var/lib/readarr/readarr.pfx'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'file.yml'
      vars:
        test_name: 'Default | verify | /var/lib/readarr/readarr.pfx'
        test_file: '/var/lib/readarr/readarr.pfx'
        test_owner: '{{ omit }}'
        test_group: '{{ omit }}'
        test_mode: '{{ omit }}'
        test_state: 'absent'

    - name: 'Default | verify | /data/media'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'file.yml'
      vars:
        test_name: 'Default | verify | /data/media'
        test_file: '/data/media'
        test_owner: 'media'
        test_group: 'media'
        test_mode: '0755'
        test_state: 'directory'
