---
- name: 'Converge'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Converge | apply r_pufky.arr.readarr'
      ansible.builtin.include_role:
        name: 'r_pufky.arr.readarr'

- name: 'Converge | toggle updates'
  hosts: 'readarr-debian-13-update_mechanisms-toggle'
  gather_facts: false
  tasks:
    - name: >-
        Converge | toggle updates |
        apply r_pufky.arr.readarr
      ansible.builtin.include_role:
        name: 'r_pufky.arr.readarr'
      vars:
        readarr_cfg_update_mechanism: true
