---
- name: 'Update mechanisms | prepare'
  hosts: 127.0.0.1
  connection: local
  gather_facts: false
  tasks:
    - name: 'Update mechanisms | prepare | create cache'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'create_cache.yml'
      vars:
        test_name: 'Update mechanisms | prepare | create cache'

    - name: 'Update mechanisms | prepare | check 0.4.10.2734'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'cache_url.yml'
      vars:
        test_name: 'Update mechanisms | prepare | cache 0.4.10.2734'
        test_dest: 'Readarr.develop.0.4.10.2734.linux-core-x64.tar.gz'
        test_url: '{{
            "https://github.com/Readarr/Readarr/releases/download/" ~
            "v0.4.10.2734/" ~
            "Readarr.develop.0.4.10.2734.linux-core-x64.tar.gz"
          }}'
        test_mode: '0640'
